# Generated by Django 5.2.7 on 2025-10-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('capital', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('population', models.BigIntegerField()),
                ('currency_code', models.CharField(blank=True, db_index=True, max_length=3, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('estimated_gdp', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('flag_url', models.URLField(blank=True, null=True)),
                ('last_refreshed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-estimated_gdp'],
                'indexes': [models.Index(fields=['name'], name='countries_c_name_67e711_idx'), models.Index(fields=['region'], name='countries_c_region_927116_idx'), models.Index(fields=['currency_code'], name='countries_c_currenc_0c881d_idx')],
            },
        ),
    ]
